<?php

namespace Database\Seeders;

use App\Models\Products;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */


    public function run(): void
    {
        $products = [
            [
                'name' => 'Productivity Suite',
                'description' => 'A comprehensive suite for productivity, including word processing, spreadsheets, and presentations.',
                'price' => 49.99,
                'image' => 'images/productivity-suite.jpg', // Assuming subcategory with ID 1 exists
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 1, // Assuming author with ID 1 exists
                'star_rating' => 4,
                'release_date' => '2023-01-15',
                'last_updated' => '2023-12-20',
                'total_user' => 10000,
                'total_download' => 5000,
                'platform_id' => 1, // Assuming platform with ID 1 exists
                'product_url' => 'https://example.com/productivity-suite',
                'status' => 'active',
                'tags' => 'productivity,office,tools',
                'creator' => 'Tech Innovators',
                'publisher' => 'Global Software Inc.',
                'developer' => 'Tech Innovators',
                'notes' => 'Recommended for small businesses and students.',
                'version' => 3,
                'size' => 250,
                'barcode' => '123456789012',
                'order' => 1,
                'featured' => true,
                'slug' => Str::slug('Productivity Suite'),
            ],
            [
                'name' => 'Graphic Designer Pro',
                'description' => 'An advanced graphic design tool for professionals.',
                'price' => 99.99,
                'image' => 'images/graphic-designer-pro.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 1,
                'star_rating' => 5,
                'release_date' => '2022-05-10',
                'last_updated' => '2023-11-10',
                'total_user' => 15000,
                'total_download' => 8000,
                'platform_id' => 2,
                'product_url' => 'https://example.com/graphic-designer-pro',
                'status' => 'active',
                'tags' => 'graphics,design,professional',
                'creator' => 'Creative Minds',
                'publisher' => 'Artware Solutions',
                'developer' => 'Creative Minds',
                'notes' => 'Perfect for professional designers and agencies.',
                'version' => 5,
                'size' => 500,
                'barcode' => '987654321098',
                'order' => 2,
                'featured' => true,
                'slug' => Str::slug('Graphic Designer Pro'),
            ],
            [
                'name' => 'Puzzle Adventures',
                'description' => 'An engaging puzzle game for all ages.',
                'price' => 9.99,
                'image' => 'images/puzzle-adventures.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 2,
                'star_rating' => 4,
                'release_date' => '2021-03-20',
                'last_updated' => '2023-01-10',
                'total_user' => 20000,
                'total_download' => 12000,
                'platform_id' => 3,
                'product_url' => 'https://example.com/puzzle-adventures',
                'status' => 'active',
                'tags' => 'games,puzzle,family',
                'creator' => 'Game Factory',
                'publisher' => 'FunTime Studios',
                'developer' => 'Game Factory',
                'notes' => 'Great for family entertainment and brain training.',
                'version' => 2,
                'size' => 120,
                'barcode' => '112233445566',
                'order' => 3,
                'featured' => false,
                'slug' => Str::slug('Puzzle Adventures'),
            ],
            [
                'name' => 'Online Learning Platform',
                'description' => 'A flexible learning platform for online education.',
                'price' => 29.99,
                'image' => 'images/online-learning-platform.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 3,
                'star_rating' => 4,
                'release_date' => '2022-09-05',
                'last_updated' => '2023-02-15',
                'total_user' => 30000,
                'total_download' => 18000,
                'platform_id' => 4,
                'product_url' => 'https://example.com/online-learning-platform',
                'status' => 'active',
                'tags' => 'education,online,learning',
                'creator' => 'Learning Experts',
                'publisher' => 'EduTech Solutions',
                'developer' => 'Learning Experts',
                'notes' => 'Great for students and professionals.',
                'version' => 4,
                'size' => 300,
                'barcode' => '789012345678',
                'order' => 4,
                'featured' => true,
                'slug' => Str::slug('Online Learning Platform'),
            ],
            [
                'name' => 'Social Media Analytics',
                'description' => 'A tool for analyzing social media engagement.',
                'price' => 49.99,
                'image' => 'images/social-media-analytics.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 1,
                'star_rating' => 4,
                'release_date' => '2021-08-12',
                'last_updated' => '2023-01-25',
                'total_user' => 10000,
                'total_download' => 8000,
                'platform_id' => 5,
                'product_url' => 'https://example.com/social-media-analytics',
                'status' => 'active',
                'tags' => 'analytics,social media,marketing',
                'creator' => 'Social Insights',
                'publisher' => 'DataWorks',
                'developer' => 'Social Insights',
                'notes' => 'Ideal for marketers and business analysts.',
                'version' => 3,
                'size' => 250,
                'barcode' => '998877665544',
                'order' => 5,
                'featured' => false,
                'slug' => Str::slug('Social Media Analytics'),
            ],
            [
                'name' => 'Virtual Reality Explorer',
                'description' => 'Experience virtual reality with this immersive tool.',
                'price' => 59.99,
                'image' => 'images/virtual-reality-explorer.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 2,
                'star_rating' => 5,
                'release_date' => '2022-11-30',
                'last_updated' => '2023-01-05',
                'total_user' => 5000,
                'total_download' => 4500,
                'platform_id' => 6,
                'product_url' => 'https://example.com/virtual-reality-explorer',
                'status' => 'active',
                'tags' => 'virtual reality,vr,exploration',
                'creator' => 'VR Innovators',
                'publisher' => 'TechVision',
                'developer' => 'VR Innovators',
                'notes' => 'Perfect for VR enthusiasts and explorers.',
                'version' => 1,
                'size' => 700,
                'barcode' => '554433221100',
                'order' => 6,
                'featured' => true,
                'slug' => Str::slug('Virtual Reality Explorer'),
            ],
            [
                'name' => 'E-commerce Platform Plus',
                'description' => 'An advanced platform for e-commerce businesses.',
                'price' => 99.99,
                'image' => 'images/e-commerce-platform-plus.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 1,
                'star_rating' => 4,
                'release_date' => '2022-07-15',
                'last_updated' => '2023-02-20',
                'total_user' => 8000,
                'total_download' => 6000,
                'platform_id' => 7,
                'product_url' => 'https://example.com/e-commerce-platform-plus',
                'status' => 'active',
                'tags' => 'e-commerce,retail,business',
                'creator' => 'Commerce Experts',
                'publisher' => 'BizTech',
                'developer' => 'Commerce Experts',
                'notes' => 'Ideal for online retailers and businesses.',
                'version' => 2,
                'size' => 400,
                'barcode' => '667788990011',
                'order' => 7,
                'featured' => false,
                'slug' => Str::slug('E-commerce Platform Plus'),
            ],
            [
                'name' => 'Fitness Tracker Pro',
                'description' => 'A comprehensive fitness tracking application.',
                'price' => 19.99,
                'image' => 'images/fitness-tracker-pro.jpg',
                'category_id' => 1,
                'subcategory_id' => 1,
                'author_id' => 1,
                'star_rating' => 5,
                'release_date' => '2020-06-10',
                'last_updated' => '2023-01-15',
                'total_user' => 15000,
                'total_download' => 12000,
                'platform_id' => 8,
                'product_url' => 'https://example.com/fitness-tracker-pro',
                'status' => 'active',
                'tags' => 'fitness,tracking,health',
                'creator' => 'Health Innovations',
                'publisher' => 'Wellness Corp',
                'developer' => 'Health Innovations',
                'notes' => 'Great for fitness enthusiasts and athletes.',
                'version' => 3,
                'size' => 150,
                'barcode' => '223344556677',
                'order' => 8,
                'featured' => true,
                'slug' => Str::slug('Fitness Tracker Pro'),
            ]
        ];

        foreach ($products as $product) {
            Products::create($product);
        }
    }
}
